services:
  - type: web
    name: app_web
    runtime: python
    repo: https://github.com/SaulVVelazquez/aplicacion_web
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py 8090
    rootDir: ./web

  - type: web
    name: api_rest
    runtime: python
    repo: https://github.com/SaulVVelazquez/api_rest
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload --port 8050
    rootDir: ./app